export { linearSearch } from './linearSearch'
export { bubbleSort } from './bubbleSort.js'
export { selectionSort } from './selectionSort.js'
export { insertionSort } from './insertionSort.js'
export { quickSort } from './quickSort.js'
export {generateRandomArray} from './generateRandomArray'
